name: flutter_template
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  easy_localization: ^3.0.6
  shared_preferences: ^2.2.3
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0

  flutter_riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.8
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
